name: 'CI Publish to NPM Registry'

on:
  workflow_dispatch:
  push:
    tags:
      - 'release/*'

permissions:
  id-token: write  # Allows OIDC to be used for trusted publishing to NPM, per https://docs.npmjs.com/trusted-publishers
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false

jobs:
  compile-test-and-publish-to-npm:
    runs-on: ubuntu-latest
    environment: ci-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
          scope: '@dalet-oss'

      - name: Update npm (11.5.1 or later is required for Github OIDC trusted publishing)
        run: npm install -g npm@latest

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Publish to public NPM registry
        run: ./publish.sh
