name: 'CI Publish to NPM Registry'

on:
  workflow_dispatch:
  push:
    tags:
      - 'release/*'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false

jobs:
  compile-test-and-publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
          scope: '@dalet-oss'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Publish to public NPM registry
        run: ./publish.sh
        env:
          NPM_REGISTRY_ACCESS_TOKEN: ${{ secrets.NPM_REGISTRY_ACCESS_TOKEN }}
